' Gambas module file

Public RutaPrograma As String = User.home & "/CreadorOrlas/" ''ruta donde estan los archivos de datos y de trabajo temporal del programa
Public RutaDatos As String '' ruta donde esta el proyecto
Public Rutas As New String[] ''rutas de trabajo
Public DatosOrla As New ClassDatosOrla

Public Sub iniciarDirectorios()
  
  rutas.add(RutaPrograma)
  rutas.add(RutaPrograma & "plantillasOrla")
  rutas.add(RutaPrograma & "temporales")
  rutas.add(RutaPrograma & "temporales/FotosAlumnos")
  rutas.add(RutaPrograma & "temporales/FotosAlumnosMini")
  rutas.Add(RutaPrograma & "temporales/FotosProfesores")
  rutas.add(RutaPrograma & "temporales/FotosProfesoresMini")
  rutas.Add(RutaPrograma & "temporales/FotosPlantillaOrla")
  rutas.Add(RutaPrograma & "trabjotmp")
  rutas.Add(RutaPrograma & "trabjotmp/pdf")
  rutas.Add(RutaPrograma & "trabjotmp/exportar")
  rutas.Add(RutaPrograma & "trabjotmp/importar")
  
  ModuleIntermedio.IniciarLaPrimeraVez(rutas)
  
  ModuleGestionAlumnos.guardado = True
  ModuleGestionProfesores.guardado = True
  
  ModuleGestionAlumnos.lista.Registros.Clear()
  ModuleGestionProfesores.lista.Registros.Clear()
  
End

Public Sub AbrirFichero(nombre As String, NombreCarpetaPrograma As String) As Boolean
  
End

Public Sub CargarDatos() As Boolean ''fichero de datos a cargar
  
End
' ---------------------------------------------------
' Guardar Datos
' ---------------------------------------------------

Public Sub guardarDatos() As Boolean
  
End

Public Sub copiarplantillas() As Boolean
  
End

Public Sub comprimirDatos() As Boolean
  
End
