' Gambas module file

'
' --------------------------
' Dibujar
'--------------------------

Public Sub dibujarSVG(ruta As String, AreaDibujo As Object) 'DrawingArea)

  Dim hbrush As PaintBrush
  Dim himage As Image
  Dim escalax As Float

  If Exist(ruta) Then
    himage = Image.Load(ruta)

    'Solo si es un area de dibujo...
    'AreaDibujo.Cached = True
    '   AreaDibujo.Border = 1

    '  AreaDibujo.Painted = True

    Paint.Begin(AreaDibujo)

    hbrush = Paint.Image(himage)
    hbrush.Translate(0, 0)
    escalax = AreaDibujo.W / himage.Width
    paint.Scale(escalax, escalax)

    Paint.Brush = hbrush
    Paint.Rectangle(0, 0, himage.w, himage.h)
    Paint.Fill()
    Paint.End
  Else
    Return
  Endif

End
