' Gambas module file

Public Sub IniciarLaPrimeraVez(rutaSprograma As String[]) ''Pasar lista de rutas a crear...siendo la 0 la ruta del programa
  
  Dim a As Integer 'contador para bucle For...Next
  ' User.Home & "/ConstructorDiplomas/"
  'Crear Directorios del trabajo Actual
  For a = 0 To rutaSprograma.count - 1 
    If Not Exist(rutaSprograma[a]) Then Mkdir rutaSprograma[a]
  Next
  
  copiarPlantillasInternas()
  
  ModuleHacerTransparente.copiarScriptTransparente(ModulePrincipal.RutaPrograma)
  'borrar datos anteriores
  
  borradoDatosAnteriores(rutaSprograma.Extract(1, rutaSprograma.max))
  
End

Public Sub copiarPlantillasInternas()
  
  Dim a As Integer
  
  For a = 1 To 2 'orlas que tengo en plantillas
    If Not Exist(ModulePrincipal.RutaPrograma & "plantillasOrla/orla" & Str$(a)) Then 
      Mkdir ModulePrincipal.RutaPrograma & "plantillasOrla/orla" & Str$(a)
      ModuleUtilidadesDisco.CopiarFicheros("Plantillas/orla" & Str$(a), ModulePrincipal.RutaPrograma & "plantillasOrla/orla" & Str$(a), "*.*")
    Endif
  Next
  
End

Public Sub borradoDatosAnteriores(rutas As String[])
  
  Dim a As Integer
  
  For a = 0 To rutas.count - 1 
    ModuleUtilidadesDisco.vaciarDirectorio(rutas[a])
  Next
  
End

Public Sub IniciarGridViewRegistrosProfesoresores(grid As ClassSuperGridview)
  
  With grid 
    .header = 3 
    .rows.count = 1000 
    .columns.count = 5
    .columns[0].title = "Foto "
    .Columns[1].title = "Nombre" 
    .Columns[2].title = "Apellidos" 
    .Columns[3].title = "Orden" 
    .Columns[4].title = "Asignatura" 
    .Columns[0].width = 50 
    .Columns[1].width = 75 
    .Columns[2].width = 125 
    .Columns[3].width = 50 
    .Columns[4].width = 75 
    
    .font.name = "Sans" 
    .font.size = 9 
    .mode = 1
    .w = 485
    .h = 500
    .x = 10
    .y = 40
    .TOOLTIP = "Si haces doble click en una fila, la puedes editar"
  End With
  
End

Public Sub IniciarGridViewRegistrosAlumnos(grid As ClassSuperGridview)
  
  With grid 
    .header = 3 
    .rows.count = 1000 
    .columns.count = 6
    .columns[0].title = "Foto "
    .Columns[1].title = "Nombre" 
    .Columns[2].title = "Apellidos" 
    .Columns[3].title = "Orden" 
    .Columns[4].title = "Pueblo" 
    .Columns[5].title = "Provincia" 
    .Columns[0].width = 50 
    .Columns[1].width = 75 
    .Columns[2].width = 125 
    .Columns[3].width = 50 
    .Columns[4].width = 75 
    .Columns[5].width = 75 
    
    .font.name = "Sans" 
    .font.size = 9 
    .mode = 1
    .w = 510
    .h = 500
    .x = 10
    .y = 40
    .TOOLTIP = "Si haces doble click en una fila, la puedes editar"
  End With
  
End
