' Gambas module file

Public RutaPrograma As String = User.home & "/CreadorOrlas/" ''ruta donde estan los archivos de datos y de trabajo temporal del programa
Public RutaDatos As String '' ruta donde esta el proyecto
Public Rutas As New String[] ''rutas de trabajo
Public DatosOrla As New ClassDatosOrla
Public alumno93 As String = "/tmp/Alu93x113.png"
Public formaElipse As String = "/tmp/elipse.png"
Public formaCuna As String = "/tmp/formacuna.png"
Public formaV As String = "/tmp/V.png"

Public Sub iniciarDirectorios()
  
  rutas.add(RutaPrograma)
  rutas.add(RutaPrograma & "plantillasOrla")
  rutas.add(RutaPrograma & "temporales")
  rutas.add(RutaPrograma & "temporales/FotosAlumnos")
  rutas.add(RutaPrograma & "temporales/FotosAlumnosMini")
  rutas.Add(RutaPrograma & "temporales/FotosProfesores")
  rutas.add(RutaPrograma & "temporales/FotosProfesoresMini")
  rutas.Add(RutaPrograma & "temporales/FotosPlantillaOrla")
  rutas.Add(RutaPrograma & "trabajotmp")
  rutas.Add(RutaPrograma & "trabajotmp/pdf")
  rutas.Add(RutaPrograma & "trabajotmp/exportar")
  rutas.Add(RutaPrograma & "trabajotmp/importar")
  rutas.Add(RutaPrograma & "trabajotmp/imagenes")
  
  ModuleIntermedio.IniciarLaPrimeraVez(rutas)
  
  ModuleGestionAlumnos.guardado = True
  ModuleGestionProfesores.guardado = True
  ModuleGestionOrla.guardado = True
  
  ModuleGestionAlumnos.lista.Registros.Clear()
  ModuleGestionProfesores.lista.Registros.Clear()
  
End

Public Sub AbrirFichero(nombre As String, NombreCarpetaPrograma As String) As Boolean
  
End

Public Sub CargarDatos() As Boolean ''fichero de datos a cargar
  
End
' ---------------------------------------------------
' Guardar Datos
' ---------------------------------------------------

Public Sub guardarDatos() As Boolean
  
  Dim contenidoAlumnos As String
  Dim contenidoProfesores As String
  Dim contenidoOrlas As String
  
  Dim resultado As Boolean
  'creo fichero de datos...
  If RutaDatos = "" Then 
    Message.Error(("Nombre de archivo incorrecto"))
    Return False
  Endif
  
  contenidoAlumnos = "version 1" & "\n" & ModuleGestionAlumnos.Lista.contenido()
  File.Save(rutaprograma & "temporales/datosALumnos.txt", contenidoAlumnos)
  
  contenidoProfesores = "version 1" & "\n" & ModuleGestionProfesores.Lista.contenido()
  File.Save(rutaprograma & "temporales/datosProfesores.txt", contenidoProfesores)
  
  contenidoOrlas = "version 1" & "\n" & ModuleGestionOrla.orla.contenido()
  File.Save(rutaprograma & "temporales/datosOrla.txt", contenidoOrlas)
  
  'copia de plantillas...
  resultado = copiarplantillas()
  If resultado = False Then Message.Error(("Problemas al copiar la plantilla de la orla"))
  resultado = comprimirDatos() 
  If resultado = False Then Message.Error(("Problemas al comprimir datos"))
  Return resultado
  
End

Public Sub copiarplantillas() As Boolean
  
  Dim nombredestino As String = User.home & "/CreadorOrlas/temporales/" & ModuleUtilidadesDisco.extraedesdebarra(ModuleGestionOrla.orla.Plantilla)
  
  If Exist(nombredestino) Then 
    Kill nombredestino
  Endif
  
  Copy ModuleGestionOrla.orla.Plantilla To User.home & "/CreadorOrlas/temporales/" & ModuleUtilidadesDisco.extraedesdebarra(ModuleGestionOrla.orla.Plantilla)
  Return True
  
End

Public Sub comprimirDatos() As Boolean

  Dim zip As New ClassZip
  
  If Exist("/tmp/temporal.zip") Then Kill "/tmp/temporal.zip"
  
  zip.comprimirDatos(rutaprograma & "temporales/FotosAlumnos")
  zip.comprimirDatos(rutaprograma & "temporales/FotosAlumnosMini")
  zip.comprimirDatos(rutaprograma & "temporales/FotosPlantillaOrla")
  zip.comprimirDatos(rutaprograma & "temporales/FotosProfesores")
  zip.comprimirDatos(rutaprograma & "temporales/FotosProfesoresMini")
  zip.comprimirDatos(rutaprograma & "temporales")
  
  If Exist(RutaDatos & ".Orla") Then 
    'existe, lo borro para actualizarlo
    Try Kill RutaDatos & ".Orla"
  Endif
  
  Try Copy "/tmp/temporal.zip" To RutaDatos & ".Orla"
  If Error Then 
    Message.Error(("Error al intentar copiar el archivo comprimido temporal al archivo final"))
    Return False
  Endif
  ModuleGestionAlumnos.guardado = True
  ModuleGestionOrla.guardado = True
  ModuleGestionProfesores.guardado = True
  Return True

End
