' Gambas module file

Public Sub IniciarLaPrimeraVez(rutaSprograma As String[]) ''Pasar lista de rutas a crear...siendo la 0 la ruta del programa
  
  Dim a As Integer 'contador para bucle For...Next
  ' User.Home & "/ConstructorDiplomas/"
  'Crear Directorios del trabajo Actual
  For a = 0 To rutaSprograma.count - 1 
    If Not Exist(rutaSprograma[a]) Then Mkdir rutaSprograma[a]
  Next
  
  copiarPlantillasInternas()
  
  ModuleHacerTransparente.copiarScriptTransparente(ModulePrincipal.RutaPrograma)
  'borrar datos anteriores
  
  borradoDatosAnteriores(rutaSprograma.Extract(1, rutaSprograma.max))
  
End

Public Sub copiarPlantillasInternas()
  
  Dim a As Integer
  
  For a = 1 To 2 'orlas que tengo en plantillas
    Try Mkdir ModulePrincipal.RutaPrograma & "plantillasOrla/orla" & Str$(a)
    ModuleUtilidadesDisco.CopiarFicherosInterna("Plantillas/orla" & Str$(a), ModulePrincipal.RutaPrograma & "plantillasOrla/orla" & Str$(a), "*.*")
    
  Next
  
End

Public Sub borradoDatosAnteriores(rutas As String[])
  
  Dim a As Integer
  
  For a = 0 To rutas.count - 1 
    ModuleUtilidadesDisco.vaciarDirectorio(rutas[a])
  Next
  
End

Public Sub IniciarGridViewRegistrosProfesoresores(grid As ClassSuperGridview)
  
  With grid 
    .header = 3 
    .rows.count = 1000 
    .columns.count = 5
    .columns[0].title = "Foto "
    .Columns[1].title = "Nombre" 
    .Columns[2].title = "Apellidos" 
    .Columns[3].title = "Orden" 
    .Columns[4].title = "Asignatura" 
    .Columns[0].width = 50 
    .Columns[1].width = 75 
    .Columns[2].width = 125 
    .Columns[3].width = 50 
    .Columns[4].width = 75 
    
    .font.name = "Sans" 
    .font.size = 9 
    .mode = 1
    .w = 485
    .h = 500
    .x = 10
    .y = 40
    .TOOLTIP = "Si haces doble click en una fila, la puedes editar"
  End With
  
End

Public Sub IniciarGridViewRegistrosAlumnos(grid As ClassSuperGridview)
  
  With grid 
    .header = 3 
    .rows.count = 1000 
    .columns.count = 6
    .columns[0].title = "Foto "
    .Columns[1].title = "Nombre" 
    .Columns[2].title = "Apellidos" 
    .Columns[3].title = "Orden" 
    .Columns[4].title = "Pueblo" 
    .Columns[5].title = "Provincia" 
    .Columns[0].width = 50 
    .Columns[1].width = 75 
    .Columns[2].width = 125 
    .Columns[3].width = 50 
    .Columns[4].width = 75 
    .Columns[5].width = 75 
    
    .font.name = "Sans" 
    .font.size = 9 
    .mode = 1
    .w = 510
    .h = 500
    .x = 10
    .y = 40
    .TOOLTIP = "Si haces doble click en una fila, la puedes editar"
  End With
  
End

Public Sub rellenarGridviewsAlumnos(rejilla As ClassSuperGridview, Lista As ClassListaAlumnos)
  
  Dim regtmp As ClassAlumno
  Dim contadorPosicionFilaGrid As Integer
  
  'limpiar la rejilla de datos
  rejilla.indice.Clear()
  contadorPosicionFilaGrid = 0
  rejilla.rows.count = Lista.registros.count + 1
  
  For Each regtmp In Lista.registros
    'TODO: Añadir pequeña miniatura de imagen. Alumno
    rejilla[contadorPosicionFilaGrid, 0].text = regtmp.foto
    rejilla[contadorPosicionFilaGrid, 1].text = regtmp.nombre
    rejilla[contadorPosicionFilaGrid, 2].text = regtmp.Apellidos
    rejilla[contadorPosicionFilaGrid, 3].text = Str$(regtmp.orden)
    rejilla[contadorPosicionFilaGrid, 4].text = regtmp.Pueblo
    rejilla[contadorPosicionFilaGrid, 5].text = regtmp.Provincia
    rejilla.indice.add(regtmp.id)
    contadorPosicionFilaGrid += 1
  Next
  
  rejilla[contadorPosicionFilaGrid, 0].text = ""
  rejilla[contadorPosicionFilaGrid, 1].text = ""
  rejilla[contadorPosicionFilaGrid, 2].text = "" 
  rejilla[contadorPosicionFilaGrid, 3].text = ""
  rejilla[contadorPosicionFilaGrid, 4].text = ""
  rejilla[contadorPosicionFilaGrid, 5].text = ""
  
  rejilla.Refresh()
  
End

Public Sub rellenarGridviewsProfesores(rejilla As ClassSuperGridview, Lista As ClassListaProfesores)
  
  Dim regtmp As ClassProfesor
  Dim contadorPosicionFilaGrid As Integer
  
  'limpiar la rejilla de datos
  rejilla.indice.Clear()
  contadorPosicionFilaGrid = 0
  rejilla.rows.count = Lista.registros.count + 1
  
  For Each regtmp In Lista.registros
    'TODO: Añadir pequeña miniatura de imagen. Profesor
    rejilla[contadorPosicionFilaGrid, 0].text = regtmp.foto
    rejilla[contadorPosicionFilaGrid, 1].text = regtmp.nombre
    rejilla[contadorPosicionFilaGrid, 2].text = regtmp.Apellidos
    rejilla[contadorPosicionFilaGrid, 3].text = Str$(regtmp.orden)
    rejilla[contadorPosicionFilaGrid, 4].text = regtmp.Asignatura
    rejilla.indice.add(regtmp.id)
    contadorPosicionFilaGrid += 1
  Next
  
  rejilla[contadorPosicionFilaGrid, 0].text = ""
  rejilla[contadorPosicionFilaGrid, 1].text = ""
  rejilla[contadorPosicionFilaGrid, 2].text = "" 
  rejilla[contadorPosicionFilaGrid, 3].text = ""
  rejilla[contadorPosicionFilaGrid, 4].text = ""
  
  rejilla.Refresh()
  
End
